/**
 * Tests for src/commands/review-prs.js
 * Tests: classification logic, review checklist, output format, edge cases
 */

import { describe, it } from 'node:test';
import assert from 'node:assert';
import {
  reviewPR,
  registerReviewPRTools,
} from '../src/commands/review-prs.js';

// ─── Helpers ─────────────────────────────────────────────────────────────────

function createMockServer() {
  const tools = {};
  return {
    server: {
      tool: (name, desc, schema, handler) => {
        tools[name] = { desc, schema, handler };
      },
    },
    tools,
  };
}

// ─── Registration tests ──────────────────────────────────────────────────────

describe('review-prs tool registration', () => {
  it('registers review_pr tool', () => {
    const { server, tools } = createMockServer();
    registerReviewPRTools(server);
    assert.ok(tools.review_pr, 'Tool should be registered');
    assert.ok(tools.review_pr.handler, 'Handler should exist');
    assert.ok(tools.review_pr.desc, 'Tool should have description');
  });
});

// ─── Classification tests ────────────────────────────────────────────────────

describe('Classification logic', () => {
  it('classifies bot-generated PR as slop', () => {
    const result = reviewPR({
      title: 'Automated dependency update',
      body: 'This PR was generated by bot',
      additions: 600,
      deletions: 400,
    });
    assert.strictEqual(result.classification, 'slop');
    assert.strictEqual(result.verdict, 'HALT');
    assert.strictEqual(result.merge_ready, false);
  });

  it('classifies empty PR as slop', () => {
    const result = reviewPR({
      pr_number: 1,
      additions: 0,
      deletions: 0,
    });
    assert.strictEqual(result.classification, 'slop');
    assert.strictEqual(result.verdict, 'HALT');
  });

  it('does not classify trivial PR as slop when it has changes', () => {
    const result = reviewPR({
      pr_number: 1,
      additions: 2,
      deletions: 1,
    });
    // Small PRs with actual changes are not slop — only truly empty PRs are
    assert.notStrictEqual(result.classification, 'slop');
  });

  it('does not classify small PR with body as slop', () => {
    const result = reviewPR({
      pr_number: 1,
      additions: 2,
      deletions: 1,
      body: 'Fix typo in README',
    });
    assert.notStrictEqual(result.classification, 'slop');
  });

  it('classifies stale PR as superseded', () => {
    const oldDate = new Date();
    oldDate.setDate(oldDate.getDate() - 90);
    const result = reviewPR({
      pr_number: 1,
      updated_at: oldDate.toISOString(),
      state: 'open',
    });
    assert.strictEqual(result.classification, 'superseded');
    assert.strictEqual(result.verdict, 'WARN');
  });

  it('does not classify recent PR as superseded', () => {
    const result = reviewPR({
      pr_number: 1,
      updated_at: new Date().toISOString(),
      state: 'open',
    });
    assert.notStrictEqual(result.classification, 'superseded');
  });

  it('classifies duplicate-titled PR as superseded', () => {
    const result = reviewPR({
      pr_number: 1,
      title: 'Supersedes #42',
    });
    assert.strictEqual(result.classification, 'superseded');
  });

  it('classifies PR with failing CI as blocker', () => {
    const result = reviewPR({
      pr_number: 1,
      ci_status: 'failure',
      additions: 50,
      deletions: 10,
      body: 'Add feature',
    });
    assert.strictEqual(result.classification, 'blocker');
    assert.strictEqual(result.verdict, 'HALT');
  });

  it('classifies PR with error CI as blocker', () => {
    const result = reviewPR({
      pr_number: 1,
      ci_status: 'error',
      additions: 50,
      deletions: 10,
    });
    assert.strictEqual(result.classification, 'blocker');
  });

  it('classifies PR with merge conflicts as blocker', () => {
    const result = reviewPR({
      pr_number: 1,
      has_merge_conflicts: true,
      additions: 100,
      deletions: 50,
    });
    assert.strictEqual(result.classification, 'blocker');
    assert.strictEqual(result.verdict, 'HALT');
  });

  it('classifies PR with security findings as blocker', () => {
    const result = reviewPR({
      pr_number: 1,
      diff_content: 'const x = eval(userInput)',
      sast_findings: [
        { severity: 'critical', ruleId: 'SEC001', message: 'Eval injection' },
      ],
      additions: 10,
      deletions: 5,
    });
    assert.strictEqual(result.classification, 'blocker');
    assert.strictEqual(result.verdict, 'HALT');
  });

  it('classifies normal PR as worthy', () => {
    const result = reviewPR({
      pr_number: 42,
      title: 'Add unit tests for auth module',
      body: 'This PR adds comprehensive tests for the authentication module.',
      additions: 150,
      deletions: 10,
      ci_status: 'success',
      has_merge_conflicts: false,
      diff_content: 'function add(a, b) { return a + b; }',
      has_tests: true,
    });
    assert.strictEqual(result.classification, 'worthy');
    assert.strictEqual(result.verdict, 'PASS');
    assert.strictEqual(result.merge_ready, true);
  });
});

// ─── Review checklist tests ──────────────────────────────────────────────────

describe('Review checklist', () => {
  it('CI status pass when success', () => {
    const result = reviewPR({
      pr_number: 1,
      ci_status: 'success',
      additions: 50,
      deletions: 10,
    });
    const ci = result.checklist.find((c) => c.id === 'ci_status');
    assert.strictEqual(ci.status, 'pass');
  });

  it('CI status warn when pending', () => {
    const result = reviewPR({
      pr_number: 1,
      ci_status: 'pending',
      additions: 50,
      deletions: 10,
    });
    const ci = result.checklist.find((c) => c.id === 'ci_status');
    assert.strictEqual(ci.status, 'warn');
  });

  it('CI status fail when failure', () => {
    const result = reviewPR({
      pr_number: 1,
      ci_status: 'failure',
      additions: 50,
      deletions: 10,
    });
    const ci = result.checklist.find((c) => c.id === 'ci_status');
    assert.strictEqual(ci.status, 'fail');
  });

  it('CI status warn when missing', () => {
    const result = reviewPR({
      pr_number: 1,
      additions: 50,
      deletions: 10,
    });
    const ci = result.checklist.find((c) => c.id === 'ci_status');
    assert.strictEqual(ci.status, 'warn');
  });

  it('merge conflicts detected', () => {
    const result = reviewPR({
      pr_number: 1,
      has_merge_conflicts: true,
      additions: 50,
      deletions: 10,
    });
    const mc = result.checklist.find((c) => c.id === 'merge_conflicts');
    assert.strictEqual(mc.status, 'fail');
  });

  it('no merge conflicts', () => {
    const result = reviewPR({
      pr_number: 1,
      has_merge_conflicts: false,
      additions: 50,
      deletions: 10,
    });
    const mc = result.checklist.find((c) => c.id === 'merge_conflicts');
    assert.strictEqual(mc.status, 'pass');
  });

  it('security scan passes on clean diff', () => {
    const result = reviewPR({
      pr_number: 1,
      diff_content: 'function add(a, b) { return a + b; }',
      additions: 5,
      deletions: 0,
    });
    const sc = result.checklist.find((c) => c.id === 'security_scan');
    assert.strictEqual(sc.status, 'pass');
  });

  it('security scan fails on dangerous code', () => {
    const result = reviewPR({
      pr_number: 1,
      diff_content: 'const result = eval(userInput)',
      additions: 1,
      deletions: 0,
    });
    const sc = result.checklist.find((c) => c.id === 'security_scan');
    assert.strictEqual(sc.status, 'fail');
    assert.ok(sc.message.includes('critical/high'));
  });

  it('security scan warns when no diff provided', () => {
    const result = reviewPR({
      pr_number: 1,
      additions: 10,
      deletions: 5,
    });
    const sc = result.checklist.find((c) => c.id === 'security_scan');
    assert.strictEqual(sc.status, 'warn');
  });

  it('code quality warn on large PR', () => {
    const result = reviewPR({
      pr_number: 1,
      additions: 800,
      deletions: 300,
    });
    const cq = result.checklist.find((c) => c.id === 'code_quality');
    assert.strictEqual(cq.status, 'warn');
    assert.ok(cq.message.includes('1100'));
  });

  it('code quality pass on reasonable PR', () => {
    const result = reviewPR({
      pr_number: 1,
      additions: 50,
      deletions: 10,
    });
    const cq = result.checklist.find((c) => c.id === 'code_quality');
    assert.strictEqual(cq.status, 'pass');
  });

  it('test coverage pass when tests included', () => {
    const result = reviewPR({
      pr_number: 1,
      has_tests: true,
      additions: 50,
      deletions: 10,
    });
    const tc = result.checklist.find((c) => c.id === 'test_coverage');
    assert.strictEqual(tc.status, 'pass');
  });

  it('test coverage fail when no tests', () => {
    const result = reviewPR({
      pr_number: 1,
      has_tests: false,
      additions: 50,
      deletions: 10,
    });
    const tc = result.checklist.find((c) => c.id === 'test_coverage');
    assert.strictEqual(tc.status, 'fail');
  });
});

// ─── Output format tests ─────────────────────────────────────────────────────

describe('Output format', () => {
  it('returns correct structure for worthy PR', () => {
    const result = reviewPR({
      pr_number: 42,
      repo: 'owner/repo',
      title: 'Add tests',
      additions: 100,
      deletions: 10,
      ci_status: 'success',
      has_merge_conflicts: false,
      has_tests: true,
    });

    assert.strictEqual(typeof result.verdict, 'string');
    assert.strictEqual(typeof result.classification, 'string');
    assert.ok(Array.isArray(result.issues));
    assert.strictEqual(typeof result.recommendation, 'string');
    assert.strictEqual(typeof result.merge_ready, 'boolean');
    assert.ok(Array.isArray(result.checklist));
    assert.ok(result.repo);
    assert.strictEqual(result.pr_number, 42);
  });

  it('verdict is one of PASS|WARN|HALT', () => {
    const result = reviewPR({
      pr_number: 1,
      additions: 50,
      deletions: 10,
      ci_status: 'success',
    });
    assert.ok(['PASS', 'WARN', 'HALT'].includes(result.verdict));
  });

  it('classification is one of slop|superseded|worthy|blocker', () => {
    const result = reviewPR({
      pr_number: 1,
      additions: 50,
      deletions: 10,
    });
    assert.ok(
      ['slop', 'superseded', 'worthy', 'blocker'].includes(result.classification)
    );
  });

  it('issues contain rule and message', () => {
    const result = reviewPR({
      pr_number: 1,
      ci_status: 'failure',
      additions: 50,
      deletions: 10,
    });
    if (result.issues.length > 0) {
      const issue = result.issues[0];
      assert.strictEqual(typeof issue.rule, 'string');
      assert.strictEqual(typeof issue.message, 'string');
    }
  });

  it('checklist has all expected items', () => {
    const result = reviewPR({
      pr_number: 1,
      additions: 50,
      deletions: 10,
    });
    const ids = result.checklist.map((c) => c.id);
    assert.ok(ids.includes('ci_status'));
    assert.ok(ids.includes('merge_conflicts'));
    assert.ok(ids.includes('security_scan'));
    assert.ok(ids.includes('code_quality'));
    assert.ok(ids.includes('test_coverage'));
  });

  it('merge_ready is boolean', () => {
    const result = reviewPR({ pr_number: 1 });
    assert.strictEqual(typeof result.merge_ready, 'boolean');
  });

  it('recommendation is non-empty string', () => {
    const result = reviewPR({
      pr_number: 1,
      additions: 50,
      deletions: 10,
    });
    assert.ok(result.recommendation.length > 0);
  });
});

// ─── Edge cases ──────────────────────────────────────────────────────────────

describe('Edge cases', () => {
  it('missing PR info returns HALT with error', () => {
    const result = reviewPR({});
    assert.strictEqual(result.verdict, 'HALT');
    assert.strictEqual(result.merge_ready, false);
    assert.ok(result.error);
  });

  it('unknown repo defaults to "unknown"', () => {
    const result = reviewPR({
      pr_number: 1,
      additions: 50,
      deletions: 10,
    });
    assert.strictEqual(result.repo, 'unknown');
  });

  it('parses GitHub URL correctly', () => {
    const result = reviewPR({
      pr_url: 'https://github.com/octocat/Hello-World/pull/42',
      additions: 50,
      deletions: 10,
      ci_status: 'success',
    });
    assert.strictEqual(result.repo, 'octocat/Hello-World');
    assert.strictEqual(result.pr_number, 42);
  });

  it('parses GitHub URL with trailing slash', () => {
    const result = reviewPR({
      pr_url: 'https://github.com/octocat/Hello-World/pull/99/',
      additions: 10,
      deletions: 5,
    });
    assert.strictEqual(result.repo, 'octocat/Hello-World');
    assert.strictEqual(result.pr_number, 99);
  });

  it('handles invalid GitHub URL gracefully', () => {
    const result = reviewPR({
      pr_url: 'https://not-github.com/something/pull/1',
      pr_number: 1,
      additions: 10,
      deletions: 5,
    });
    // Falls back to repo=unknown, pr_number from param
    assert.strictEqual(result.repo, 'unknown');
    assert.strictEqual(result.pr_number, 1);
  });

  it('handles all optional fields absent', () => {
    const result = reviewPR({ pr_number: 1 });
    assert.strictEqual(typeof result.verdict, 'string');
    assert.strictEqual(typeof result.classification, 'string');
    assert.ok(Array.isArray(result.checklist));
    assert.strictEqual(result.checklist.length, 5);
  });

  it('handles empty diff_content', () => {
    const result = reviewPR({
      pr_number: 1,
      diff_content: '',
      additions: 10,
      deletions: 5,
    });
    const sc = result.checklist.find((c) => c.id === 'security_scan');
    assert.strictEqual(sc.status, 'warn');
  });

  it('handles pr_number from pr_url taking precedence', () => {
    const result = reviewPR({
      pr_url: 'https://github.com/owner/repo/pull/100',
      pr_number: 200,
      additions: 50,
      deletions: 10,
    });
    assert.strictEqual(result.pr_number, 100);
    assert.strictEqual(result.repo, 'owner/repo');
  });
});

// ─── Tool handler tests ─────────────────────────────────────────────────────

describe('Tool handler', () => {
  it('returns structured response', async () => {
    const { server, tools } = createMockServer();
    registerReviewPRTools(server);

    const result = await tools.review_pr.handler({
      pr_number: 42,
      repo: 'owner/repo',
      additions: 100,
      deletions: 10,
      ci_status: 'success',
    });

    assert.ok(result.content, 'Should have content');
    assert.ok(result.content[0].text, 'Should have text content');
    assert.ok(result.reviewReport, 'Should have reviewReport');
    assert.ok(['PASS', 'WARN', 'HALT'].includes(result.reviewReport.verdict));
  });

  it('handles error gracefully', async () => {
    const { server, tools } = createMockServer();
    registerReviewPRTools(server);

    const result = await tools.review_pr.handler({});
    // Missing pr_info should return HALT, not throw
    assert.ok(result.content, 'Should have content');
    assert.ok(result.content[0].text.includes('HALT'));
  });
});
