/**
 * Test suite for typosquatting detection tool
 */

import { describe, it } from 'node:test';
import assert from 'node:assert';
import { 
  levenshteinDistance, 
  generateCandidates, 
  scoreCandidate, 
  detectTyposquat 
} from '../src/typosquat-detect.js';

describe('levenshteinDistance', () => {
  it('should return 0 for identical strings', () => {
    assert.strictEqual(levenshteinDistance('test', 'test'), 0);
  });

  it('should calculate single character deletion', () => {
    assert.strictEqual(levenshteinDistance('test', 'tes'), 1);
    assert.strictEqual(levenshteinDistance('test', 'est'), 1);
  });

  it('should calculate single character insertion', () => {
    assert.strictEqual(levenshteinDistance('tes', 'test'), 1);
    assert.strictEqual(levenshteinDistance('est', 'test'), 1);
  });

  it('should calculate single character substitution', () => {
    assert.strictEqual(levenshteinDistance('test', 'tast'), 1);
    assert.strictEqual(levenshteinDistance('test', 'best'), 1);
  });

  it('should calculate transposition (costs 2 in standard Levenshtein)', () => {
    assert.strictEqual(levenshteinDistance('ab', 'ba'), 2);
    assert.strictEqual(levenshteinDistance('abcd', 'abdc'), 2);
  });

  it('should handle empty strings', () => {
    assert.strictEqual(levenshteinDistance('', 'test'), 4);
    assert.strictEqual(levenshteinDistance('test', ''), 4);
    assert.strictEqual(levenshteinDistance('', ''), 0);
  });

  it('should calculate complex distance', () => {
    assert.strictEqual(levenshteinDistance('kitten', 'sitting'), 3);
    assert.strictEqual(levenshteinDistance('express', 'exprss'), 1);
  });
});

describe('generateCandidates', () => {
  it('should generate omission candidates', () => {
    const candidates = generateCandidates('express');
    const omissions = candidates.filter(c => c.method === 'omission');
    
    assert.ok(omissions.length > 0, 'Should have omission candidates');
    assert.ok(omissions.some(c => c.name === 'exprss'), 'Should have exprss');
    assert.ok(omissions.some(c => c.name === 'expres'), 'Should have expres');
  });

  it('should generate transposition candidates', () => {
    const candidates = generateCandidates('express');
    const transpositions = candidates.filter(c => c.method === 'transposition');
    
    assert.ok(transpositions.length > 0, 'Should have transposition candidates');
    // 'express' has 'ss' which won't be transposed (same chars)
    // but other adjacent chars should be transposed
  });

  it('should generate substitution candidates using keyboard neighbors', () => {
    const candidates = generateCandidates('test');
    const substitutions = candidates.filter(c => c.method === 'substitution');
    
    assert.ok(substitutions.length > 0, 'Should have substitution candidates');
    // t's keyboard neighbors: r, f, g, y
    assert.ok(substitutions.some(c => c.name === 'rest'), 'Should have rest (t→r)');
    assert.ok(substitutions.some(c => c.name === 'fest'), 'Should have fest (t→f)');
  });

  it('should generate insertion candidates', () => {
    const candidates = generateCandidates('ab');
    const insertions = candidates.filter(c => c.method === 'insertion');
    
    assert.ok(insertions.length > 0, 'Should have insertion candidates');
    // Should have at least some insertions
    assert.ok(insertions.some(c => c.name === 'aab'), 'Should have aab');
  });

  it('should generate separator candidates for hyphenated names', () => {
    const candidates = generateCandidates('node-fetch');
    const separators = candidates.filter(c => c.method === 'separator');
    
    assert.ok(separators.length > 0, 'Should have separator candidates');
    assert.ok(separators.some(c => c.name === 'node_fetch'), 'Should have node_fetch (separator)');
    // nodefetch may be generated by omission (removing -) rather than separator
    assert.ok(candidates.some(c => c.name === 'nodefetch'), 'Should have nodefetch in candidates');
  });

  it('should generate separator candidates for underscored names', () => {
    const candidates = generateCandidates('node_fetch');
    const separators = candidates.filter(c => c.method === 'separator');
    
    assert.ok(separators.length > 0, 'Should have separator candidates');
    assert.ok(separators.some(c => c.name === 'node-fetch'), 'Should have node-fetch');
  });

  it('should not include original name', () => {
    const candidates = generateCandidates('express');
    const names = candidates.map(c => c.name);
    
    assert.ok(!names.includes('express'), 'Should not include original name');
  });

  it('should not include duplicates', () => {
    const candidates = generateCandidates('test');
    const names = candidates.map(c => c.name);
    const uniqueNames = [...new Set(names)];
    
    assert.strictEqual(names.length, uniqueNames.length, 'Should not have duplicates');
  });

  it('should handle single character names', () => {
    const candidates = generateCandidates('a');
    
    assert.ok(candidates.length > 0, 'Should have candidates for single char');
    // Should have insertion and substitution candidates (no omission, transposition, or separator)
    const methods = new Set(candidates.map(c => c.method));
    assert.ok(methods.has('insertion'), 'Should have insertion candidates');
    assert.ok(methods.has('substitution'), 'Should have substitution candidates');
    assert.ok(!methods.has('omission'), 'Should not have omission for single char');
  });
});

describe('scoreCandidate', () => {
  it('should score high risk for very similar names', () => {
    const { score, risk } = scoreCandidate('express', 'exprss', 'omission');
    
    assert.ok(score >= 70, `Score ${score} should be >= 70 for high risk`);
    assert.strictEqual(risk, 'high');
  });

  it('should score medium risk for moderately similar names', () => {
    const { score, risk } = scoreCandidate('express', 'express-cli', 'insertion');
    
    assert.ok(score >= 40 && score < 70, `Score ${score} should be 40-69 for medium risk`);
    assert.strictEqual(risk, 'medium');
  });

  it('should score low risk for dissimilar names', () => {
    const { score, risk } = scoreCandidate('express', 'totallydifferent', 'omission');
    
    assert.ok(score < 40, `Score ${score} should be < 40 for low risk`);
    assert.strictEqual(risk, 'low');
  });
});

describe('detectTyposquat', () => {
  it('should detect high-risk typosquatting for express', () => {
    const result = detectTyposquat('express');
    
    assert.strictEqual(result.verdict, 'HALT', 'Should halt for express');
    assert.strictEqual(result.package, 'express');
    assert.ok(result.candidates.length >= 5, `Should have at least 5 candidates, got ${result.candidates.length}`);
    // All candidates should be high risk for a popular package like express
    const highRiskCount = result.candidates.filter(c => c.risk === 'high').length;
    assert.ok(highRiskCount >= 3, `Should have at least 3 high-risk candidates, got ${highRiskCount}`);
  });

  it('should return WARN or PASS for unique package names', () => {
    const result = detectTyposquat('my-unique-package-xyz-123');
    
    assert.ok(['PASS', 'WARN'].includes(result.verdict), `Should not halt for unique name, got ${result.verdict}`);
    assert.strictEqual(result.package, 'my-unique-package-xyz-123');
    // Unique names may have some candidates but should not be all high-risk
    const highRiskCount = result.candidates.filter(c => c.risk === 'high').length;
    assert.ok(highRiskCount <= 5, `Should have at most 5 high-risk candidates for unique name, got ${highRiskCount}`);
  });

  it('should handle package names with hyphens', () => {
    const result = detectTyposquat('node-fetch');
    
    assert.ok(['PASS', 'WARN', 'HALT'].includes(result.verdict), 'Should have valid verdict');
    assert.strictEqual(result.package, 'node-fetch');
    assert.ok(result.candidates.length >= 0, 'Should have candidates array');
  });

  it('should handle package names with underscores', () => {
    const result = detectTyposquat('my_package');
    
    assert.ok(['PASS', 'WARN', 'HALT'].includes(result.verdict), 'Should have valid verdict');
    assert.strictEqual(result.package, 'my_package');
  });

  it('should handle single character package names', () => {
    const result = detectTyposquat('a');
    
    assert.ok(['PASS', 'WARN', 'HALT'].includes(result.verdict), 'Should have valid verdict');
    assert.strictEqual(result.package, 'a');
    assert.ok(Array.isArray(result.candidates), 'Should have candidates array');
  });

  it('should handle very long package names', () => {
    const longName = 'a'.repeat(100);
    const result = detectTyposquat(longName);
    
    assert.ok(['PASS', 'WARN', 'HALT'].includes(result.verdict), 'Should have valid verdict');
    assert.strictEqual(result.package, longName);
  });

  it('should handle empty package name', () => {
    const result = detectTyposquat('');
    
    assert.strictEqual(result.verdict, 'PASS', 'Should pass for empty');
    assert.strictEqual(result.package, '');
    assert.strictEqual(result.candidates.length, 0, 'Should have no candidates');
  });

  it('should handle null package name', () => {
    const result = detectTyposquat(null);
    
    assert.strictEqual(result.verdict, 'PASS', 'Should pass for null');
    assert.strictEqual(result.package, '');
    assert.strictEqual(result.candidates.length, 0, 'Should have no candidates');
  });

  it('should handle undefined package name', () => {
    const result = detectTyposquat(undefined);
    
    assert.strictEqual(result.verdict, 'PASS', 'Should pass for undefined');
    assert.strictEqual(result.package, '');
    assert.strictEqual(result.candidates.length, 0, 'Should have no candidates');
  });

  it('should return structured JSON format', () => {
    const result = detectTyposquat('test');
    
    assert.ok(typeof result.verdict === 'string', 'verdict should be string');
    assert.ok(typeof result.package === 'string', 'package should be string');
    assert.ok(Array.isArray(result.candidates), 'candidates should be array');
    assert.ok(typeof result.recommendation === 'string', 'recommendation should be string');
    
    if (result.candidates.length > 0) {
      const candidate = result.candidates[0];
      assert.ok(typeof candidate.name === 'string', 'candidate name should be string');
      assert.ok(typeof candidate.distance === 'number', 'candidate distance should be number');
      assert.ok(typeof candidate.method === 'string', 'candidate method should be string');
      assert.ok(typeof candidate.risk === 'string', 'candidate risk should be string');
    }
  });

  it('should provide actionable recommendations', () => {
    const highRisk = detectTyposquat('express');
    const lowRisk = detectTyposquat('my-unique-xyz');
    
    assert.ok(highRisk.recommendation.length > 10, 'High risk should have detailed recommendation');
    assert.ok(lowRisk.recommendation.length > 10, 'Low risk should have recommendation');
    assert.ok(highRisk.recommendation.includes('typosquatting') || 
              highRisk.recommendation.includes('risk'), 
              'Recommendation should mention risk');
  });
});

describe('Known typosquatting examples', () => {
  // Known typos that are actually generated by our mutation algorithms
  const knownTypos = [
    { original: 'express', typos: ['exprss', 'expres', 'expresss'] },
    { original: 'lodash', typos: ['lodahs', 'lodsh'] },
    { original: 'react', typos: ['raect', 'reacr', 'reactt'] },
    { original: 'axios', typos: ['axois', 'axioos', 'axiios'] },
  ];

  knownTypos.forEach(({ original, typos }) => {
    it(`should generate known typosquatting candidates for ${original}`, () => {
      // Use generateCandidates directly to check full candidate set
      const candidates = generateCandidates(original);
      const candidateNames = candidates.map(c => c.name);
      
      // At least some of the known typos should be generated
      const detectedKnownTypos = typos.filter(t => candidateNames.includes(t));
      assert.ok(detectedKnownTypos.length > 0, 
        `Should generate at least one known typo for ${original}. Generated: ${candidateNames.join(', ')}`);
    });

    it(`should flag ${original} as high or medium risk`, () => {
      const result = detectTyposquat(original);
      assert.ok(['WARN', 'HALT'].includes(result.verdict), 
        `Should warn or halt for ${original}, got ${result.verdict}`);
    });
  });
});
